# fly.toml app configuration file generated for maintenance-webpage-project on 2025-10-23T19:09:39-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'maintenance-webpage-project'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  concurrency = { type = "requests", soft_limit = 20 }

  [[http_service.checks]]
    grace_period = "35s"  
    interval = "10s"
    timeout = "5s"
    method = "GET"
    path = "/"


[mounts]
  source = "uploads_data"
  destination = "/data"